[2024-08-11T03:28:00.098+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T03:28:00.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.create_dataset scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-11T03:28:00.123+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.create_dataset scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-11T03:28:00.123+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-11T03:28:00.140+0000] {taskinstance.py:2330} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_dataset> on 2024-01-01 00:00:00+00:00
[2024-08-11T03:28:00.149+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-11T03:28:00.150+0000] {standard_task_runner.py:64} INFO - Started process 74 to run task
[2024-08-11T03:28:00.150+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'create_dataset', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/googleBigQuery.py', '--cfg-path', '/tmp/tmplewym12m']
[2024-08-11T03:28:00.152+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask create_dataset
[2024-08-11T03:28:00.195+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.create_dataset scheduled__2024-01-01T00:00:00+00:00 [running]> on host b6e1331e9d6b
[2024-08-11T03:28:00.283+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='create_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-08-11T03:28:00.284+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T03:28:00.310+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-08-11T03:28:00.312+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-08-11T03:28:00.364+0000] {bigquery.py:533} INFO - datasetId was not specified in `dataset_reference`. Will use default value dataset_my_dag.
[2024-08-11T03:28:00.364+0000] {bigquery.py:533} INFO - projectId was not specified in `dataset_reference`. Will use default value bigdata-2000.
[2024-08-11T03:28:00.364+0000] {bigquery.py:544} INFO - Creating dataset: dataset_my_dag in project: bigdata-2000 
[2024-08-11T03:28:01.023+0000] {bigquery.py:2167} INFO - Dataset dataset_my_dag already exists.
[2024-08-11T03:28:01.042+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T03:28:01.050+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=create_dataset, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20240811T032800, end_date=20240811T032801
[2024-08-11T03:28:01.088+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-11T03:28:01.116+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-11T03:28:01.126+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
