[2024-08-11T03:37:03.540+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T03:37:03.563+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.create_dataset scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-08-11T03:37:03.572+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.create_dataset scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-08-11T03:37:03.573+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-11T03:37:03.597+0000] {taskinstance.py:2330} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_dataset> on 2024-02-01 00:00:00+00:00
[2024-08-11T03:37:03.609+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-11T03:37:03.610+0000] {standard_task_runner.py:64} INFO - Started process 88 to run task
[2024-08-11T03:37:03.615+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'create_dataset', 'scheduled__2024-02-01T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/googleBigQuery.py', '--cfg-path', '/tmp/tmpbx672o5_']
[2024-08-11T03:37:03.617+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask create_dataset
[2024-08-11T03:37:03.720+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.create_dataset scheduled__2024-02-01T00:00:00+00:00 [running]> on host 398299d1f2b6
[2024-08-11T03:37:03.878+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='create_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-01T00:00:00+00:00'
[2024-08-11T03:37:03.880+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T03:37:03.908+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-08-11T03:37:03.910+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-08-11T03:37:03.973+0000] {bigquery.py:533} INFO - datasetId was not specified in `dataset_reference`. Will use default value dataset_my_dag.
[2024-08-11T03:37:03.974+0000] {bigquery.py:533} INFO - projectId was not specified in `dataset_reference`. Will use default value bigdata-2000.
[2024-08-11T03:37:03.974+0000] {bigquery.py:544} INFO - Creating dataset: dataset_my_dag in project: bigdata-2000 
[2024-08-11T03:37:04.667+0000] {bigquery.py:2167} INFO - Dataset dataset_my_dag already exists.
[2024-08-11T03:37:04.710+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T03:37:04.744+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=create_dataset, run_id=scheduled__2024-02-01T00:00:00+00:00, execution_date=20240201T000000, start_date=20240811T033703, end_date=20240811T033704
[2024-08-11T03:37:04.819+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-11T03:37:04.859+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-11T03:37:04.867+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
